[94m~                                                                               [22;1H~                                                                               [23;1H~                                                                               [m[24;63H1,1[10C全部
"lab1.cpp" 20L, 204C[1;1H[?12l[?25hP+q436f\P+q6b75\P+q6b64\P+q6b72\P+q6b6c\P+q2332\P+q2334\P+q2569\P+q2a37\P+q6b31\[?25l[24;1H[K[24;1H:[?12l[?25hw[?25l[?12l[?25hq[?25l[?12l[?25h
[?25l"lab1.cpp" 20L, 204C 已寫入


[?1l>[?12l[?25h[?1049l]0;wenchongchang@jeremy4243-x550ld: ~/桌面/lab1[01;32mwenchongchang@jeremy4243-x550ld[00m:[01;34m~/桌面/lab1[00m$ g++ =o [K[K[K-o lab1 lab1.cpp
]0;wenchongchang@jeremy4243-x550ld: ~/桌面/lab1[01;32mwenchongchang@jeremy4243-x550ld[00m:[01;34m~/桌面/lab1[00m$ ./lab1
222 
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;wenchongchang@jeremy4243-x550ld: ~/桌面/lab1[01;32mwenchongchang@jeremy4243-x550ld[00m:[01;34m~/桌面/lab1[00m$ exit

命令稿已於 2017年03月14日 (週二) 07時58分38秒
 完成
